title: Коллективный блог Ruby-разработчиков
email: info@krdprog.ru
description: >- # this means to ignore newlines until "baseurl:"
  Коллективный блог Ruby-программистов. Полезные материалы по стеку Ruby, Ruby on Rails.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:title/
markdown: kramdown

kramdown:
  syntax_highlighter: coderay
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
